version: '3'
services:
  app:
    build: .
    depends_on:
      - db
    environment:
      DATABASE_URL:
      NODE_ENV: development
      PORT: 5000
    ports:
      - "5022:5000"
    command: npm run server
    volumes:
      - .:/app/

  db:
    image: postgres:latest
    ports:
      - "45432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: imperial-1